disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Debopam Gupta"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 Jan 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Debopam Gupta"
  email = "w3dg@duck.com"
  # image = "s/assets/pfp.png"
  imageQuality = 96
  headline = "Software dev & CS student. Exploring systems, the web, and sustainable tech."
  # bio = "A little bit about you" # displayed in article footers
  links = [
    { email = "mailto:w3dg@duck.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
    { bluesky = "https://bsky.app/profile/w3dg.bsky.social" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/w3dg" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/its_not_dg" },
    # { itch-io = "https://username.itch.io" },
    # { keybase = "https://keybase.io/username" },
    # { keyoxide = "https://keyoxide.org/URI" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/debopamgupta" },
    { mastodon = "https://mastodon.social/@w3dg" },
    # { matrix = "https://matrix.to/#/URI" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { orcid = "https://orcid.org/userid" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # { signal = "https://signal.me/#eu/userid" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://open.spotify.com/user/userid" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/w3_dg" },
    # { threads = "https://www.threads.net/@username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/its_not_dg" },
    # { twitter = "https://twitter.com/its_not_dg" },
    { x-twitter = "https://x.com/its_not_dg" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://www.youtube.com/@debopamgupta" },
    # { ko-fi = "https://ko-fi.com/username" },
    # { codeberg = "https://codeberg.org/username"},
  ]
